# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "iwlwifi" ];
  boot.extraModulePackages = [ ];

  boot.kernelParams = [ "button.lid_init_state=open" "pcie_aspm=off" "iwlmvm.power_scheme=1" "iwlwifi.power_save=0" "iwlwifi.uapsd_disable=1" "iwlwifi.disable_11ax=1" ];
  boot.extraModprobeConfig = ''
    options iwlwifi swcrypto=1
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5b68c7be-e240-4728-bbef-1b8f2bfe7f4e";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/5b68c7be-e240-4728-bbef-1b8f2bfe7f4e";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/5b68c7be-e240-4728-bbef-1b8f2bfe7f4e";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/5b68c7be-e240-4728-bbef-1b8f2bfe7f4e";
      fsType = "btrfs";
      options = [ "subvol=@log" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/5b68c7be-e240-4728-bbef-1b8f2bfe7f4e";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd" "noatime" "ssd" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/549C-F485";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/5b68c7be-e240-4728-bbef-1b8f2bfe7f4e";
      fsType = "btrfs";
      options = [ "subvol=@swap" "nodatacow" "noatime" "ssd" "space_cache=v2" ];
    };

  swapDevices = [
    { device = "/swap/swapfile"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
